export const mockdata = [
  {
    id: 1,
    from: "bsimkovich0@google.com",
    to: "ecallinan0@bigcartel.com",
    body: "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    date: "2019-05-22T05:22:01Z",
  },
  {
    id: 2,
    from: "aswire1@bravesites.com",
    to: "sklosa1@ibm.com",
    body: "In quis justo. Maecenas rhoncus aliquam lacus.",
    date: "2019-05-24T14:49:13Z",
  },
  {
    id: 3,
    from: "jellingsworth2@de.vu",
    to: "sembra2@ustream.tv",
    body: "In hac habitasse platea dictumst.",
    date: "2019-09-26T11:39:54Z",
  },
  {
    id: 4,
    from: "abunclark3@scribd.com",
    to: "cnockells3@slideshare.net",
    body: "In hac habitasse platea dictumst.",
    date: "2019-10-01T01:46:22Z",
  },
  {
    id: 5,
    from: "apettengell4@shinystat.com",
    to: "dlello4@cbc.ca",
    body: "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    date: "2019-12-09T18:26:44Z",
  },
  {
    id: 6,
    from: "tsporrij5@ebay.com",
    to: "wblethin5@patch.com",
    body:
      "Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    date: "2019-07-17T00:23:36Z",
  },
  {
    id: 7,
    from: "afitchew6@chronoengine.com",
    to: "aspurier6@senate.gov",
    body: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    date: "2019-09-16T04:18:23Z",
  },
  {
    id: 8,
    from: "asolomonides7@wired.com",
    to: "cthunnercliffe7@mlb.com",
    body:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    date: "2020-04-16T14:50:59Z",
  },
  {
    id: 9,
    from: "kkilpatrick8@illinois.edu",
    to: "achesman8@ifeng.com",
    body: "Phasellus id sapien in sapien iaculis congue.",
    date: "2020-04-09T02:23:40Z",
  },
  {
    id: 10,
    from: "dblindt9@godaddy.com",
    to: "daisthorpe9@unc.edu",
    body:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    date: "2019-09-18T18:46:49Z",
  },
  {
    id: 11,
    from: "aballentimea@posterous.com",
    to: "msandesona@gnu.org",
    body: "Suspendisse potenti.",
    date: "2019-05-20T01:57:38Z",
  },
  {
    id: 12,
    from: "jgiraudob@tiny.cc",
    to: "gcrockb@last.fm",
    body:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    date: "2019-07-27T10:41:46Z",
  },
  {
    id: 13,
    from: "lcastellanc@tinypic.com",
    to: "einglisc@earthlink.net",
    body: "In congue.",
    date: "2020-03-18T04:08:59Z",
  },
  {
    id: 14,
    from: "rgiacopazzid@merriam-webster.com",
    to: "jrunacresd@addthis.com",
    body: "Proin risus.",
    date: "2020-02-14T21:19:20Z",
  },
  {
    id: 15,
    from: "faldinee@army.mil",
    to: "xgriggse@state.tx.us",
    body: "Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    date: "2019-12-08T02:58:49Z",
  },
  {
    id: 16,
    from: "rczaplef@yandex.ru",
    to: "edemainef@wordpress.org",
    body: "In eleifend quam a odio. In hac habitasse platea dictumst.",
    date: "2019-09-22T16:18:59Z",
  },
  {
    id: 17,
    from: "kmacrinng@desdev.cn",
    to: "rmillierg@google.co.uk",
    body: "Duis mattis egestas metus. Aenean fermentum.",
    date: "2020-02-21T02:28:06Z",
  },
  {
    id: 18,
    from: "ncammomileh@mapquest.com",
    to: "llaydonh@canalblog.com",
    body: "Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    date: "2019-11-15T04:17:55Z",
  },
  {
    id: 19,
    from: "tmacleesei@japanpost.jp",
    to: "caughtiei@adobe.com",
    body:
      "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    date: "2020-03-16T00:50:04Z",
  },
  {
    id: 20,
    from: "apilmerj@php.net",
    to: "caldwichj@tripod.com",
    body: "Nulla mollis molestie lorem.",
    date: "2019-04-26T14:10:32Z",
  },
  {
    id: 21,
    from: "lwordsleyk@businessinsider.com",
    to: "eflintiffk@patch.com",
    body: "Pellentesque viverra pede ac diam.",
    date: "2019-08-18T11:25:29Z",
  },
  {
    id: 22,
    from: "bosboldstonel@state.tx.us",
    to: "jmencil@china.com.cn",
    body: "Nulla nisl.",
    date: "2019-08-19T12:47:40Z",
  },
  {
    id: 23,
    from: "mmaundm@yellowbook.com",
    to: "nbolesworthm@yahoo.com",
    body:
      "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    date: "2019-10-22T01:28:03Z",
  },
  {
    id: 24,
    from: "rbasindalen@acquirethisname.com",
    to: "gwhybrayn@bluehost.com",
    body:
      "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    date: "2019-07-01T23:43:03Z",
  },
  {
    id: 25,
    from: "mcowerno@sourceforge.net",
    to: "kfranklingo@skype.com",
    body: "Donec dapibus. Duis at velit eu est congue elementum.",
    date: "2019-05-26T20:17:39Z",
  },
  {
    id: 26,
    from: "qohagirtiep@stanford.edu",
    to: "jtheunissenp@irs.gov",
    body: "Nulla facilisi.",
    date: "2019-11-23T13:57:40Z",
  },
  {
    id: 27,
    from: "spotticaryq@wunderground.com",
    to: "tmugfordq@businessweek.com",
    body:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    date: "2019-10-29T14:45:35Z",
  },
  {
    id: 28,
    from: "abreydinr@usnews.com",
    to: "smckerronr@issuu.com",
    body:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    date: "2020-01-02T02:39:33Z",
  },
  {
    id: 29,
    from: "mwattss@google.com",
    to: "dolmans@cam.ac.uk",
    body: "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    date: "2020-02-29T11:08:59Z",
  },
  {
    id: 30,
    from: "cmaddisont@hhs.gov",
    to: "frimmingtont@sfgate.com",
    body:
      "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    date: "2020-03-11T18:57:15Z",
  },
  {
    id: 31,
    from: "rexonu@last.fm",
    to: "mbynethu@statcounter.com",
    body: "Proin risus. Praesent lectus.",
    date: "2019-07-31T04:13:18Z",
  },
  {
    id: 32,
    from: "gkieldv@technorati.com",
    to: "ccanelasv@hud.gov",
    body: "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    date: "2020-01-12T05:49:39Z",
  },
  {
    id: 33,
    from: "jbartaw@nbcnews.com",
    to: "hsummersettw@mashable.com",
    body: "Etiam vel augue.",
    date: "2020-03-17T05:53:41Z",
  },
  {
    id: 34,
    from: "jdrix@go.com",
    to: "tmayzesx@engadget.com",
    body: "Aenean sit amet justo. Morbi ut odio.",
    date: "2019-11-29T12:07:12Z",
  },
  {
    id: 35,
    from: "rstarfordy@stanford.edu",
    to: "dyouthedy@google.ca",
    body: "Donec ut mauris eget massa tempor convallis.",
    date: "2020-03-14T06:01:19Z",
  },
  {
    id: 36,
    from: "cprebblez@upenn.edu",
    to: "cyouensz@dagondesign.com",
    body:
      "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    date: "2019-06-12T22:24:59Z",
  },
  {
    id: 37,
    from: "sastbury10@noaa.gov",
    to: "cfullerlove10@technorati.com",
    body:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    date: "2020-03-07T00:57:42Z",
  },
  {
    id: 38,
    from: "srafter11@earthlink.net",
    to: "emcgaw11@google.com.hk",
    body:
      "Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    date: "2019-05-05T12:15:21Z",
  },
  {
    id: 39,
    from: "areckless12@squarespace.com",
    to: "cudell12@livejournal.com",
    body: "Nullam molestie nibh in lectus. Pellentesque at nulla.",
    date: "2019-10-07T23:50:20Z",
  },
  {
    id: 40,
    from: "rlidell13@prnewswire.com",
    to: "sgarber13@wsj.com",
    body: "Donec dapibus. Duis at velit eu est congue elementum.",
    date: "2020-01-03T02:06:31Z",
  },
  {
    id: 41,
    from: "sbeamish14@craigslist.org",
    to: "etrevear14@pcworld.com",
    body:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    date: "2019-05-05T03:41:31Z",
  },
  {
    id: 42,
    from: "jtomanek15@nbcnews.com",
    to: "cgoldstone15@vistaprint.com",
    body:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    date: "2020-04-11T08:05:23Z",
  },
  {
    id: 43,
    from: "cguage16@fema.gov",
    to: "spratten16@bbc.co.uk",
    body:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    date: "2019-05-23T23:10:29Z",
  },
  {
    id: 44,
    from: "lkinforth17@google.it",
    to: "kparsell17@creativecommons.org",
    body: "In quis justo.",
    date: "2020-03-20T08:52:58Z",
  },
  {
    id: 45,
    from: "ibliven18@wufoo.com",
    to: "rsyrie18@buzzfeed.com",
    body: "Suspendisse potenti.",
    date: "2019-08-23T17:51:17Z",
  },
  {
    id: 46,
    from: "averling19@bandcamp.com",
    to: "rvyvyan19@purevolume.com",
    body:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    date: "2020-01-19T15:46:19Z",
  },
  {
    id: 47,
    from: "rpea1a@businesswire.com",
    to: "rserridge1a@dot.gov",
    body: "Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    date: "2019-09-24T21:23:20Z",
  },
  {
    id: 48,
    from: "gandri1b@tinypic.com",
    to: "mkemm1b@pbs.org",
    body: "Cras pellentesque volutpat dui.",
    date: "2020-03-11T21:03:02Z",
  },
  {
    id: 49,
    from: "ctebbit1c@who.int",
    to: "llicciardello1c@joomla.org",
    body: "Cras in purus eu magna vulputate luctus.",
    date: "2019-09-02T22:42:33Z",
  },
  {
    id: 50,
    from: "bmaffulli1d@amazon.co.uk",
    to: "cballchin1d@google.com",
    body: "Pellentesque ultrices mattis odio.",
    date: "2019-12-05T23:41:07Z",
  },
  {
    id: 51,
    from: "srhys1e@ft.com",
    to: "fcaldeiro1e@paginegialle.it",
    body: "Etiam faucibus cursus urna. Ut tellus.",
    date: "2019-10-19T16:14:52Z",
  },
  {
    id: 52,
    from: "rhowkins1f@is.gd",
    to: "dburdass1f@printfriendly.com",
    body: "Praesent blandit lacinia erat.",
    date: "2020-03-18T02:22:54Z",
  },
  {
    id: 53,
    from: "cthreadgold1g@hexun.com",
    to: "tgayther1g@1und1.de",
    body: "Proin interdum mauris non ligula pellentesque ultrices.",
    date: "2019-09-06T19:22:46Z",
  },
  {
    id: 54,
    from: "ckemm1h@rediff.com",
    to: "fpull1h@trellian.com",
    body: "Nam tristique tortor eu pede.",
    date: "2019-12-30T03:59:35Z",
  },
  {
    id: 55,
    from: "bklaessen1i@sciencedirect.com",
    to: "whair1i@amazon.com",
    body: "Integer ac leo. Pellentesque ultrices mattis odio.",
    date: "2019-10-14T14:35:17Z",
  },
  {
    id: 56,
    from: "mcarmont1j@about.me",
    to: "swillimont1j@cmu.edu",
    body:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    date: "2020-01-10T23:18:00Z",
  },
  {
    id: 57,
    from: "gcorish1k@csmonitor.com",
    to: "wbalaam1k@sourceforge.net",
    body: "Nam tristique tortor eu pede.",
    date: "2019-06-19T11:53:41Z",
  },
  {
    id: 58,
    from: "lbumphrey1l@examiner.com",
    to: "redwin1l@blogspot.com",
    body: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    date: "2019-12-16T15:30:06Z",
  },
  {
    id: 59,
    from: "rridge1m@arstechnica.com",
    to: "jventuroli1m@globo.com",
    body: "Vestibulum sed magna at nunc commodo placerat.",
    date: "2020-01-16T22:53:02Z",
  },
  {
    id: 60,
    from: "fspata1n@usnews.com",
    to: "fmusso1n@hp.com",
    body:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    date: "2020-04-09T18:48:24Z",
  },
  {
    id: 61,
    from: "mforo1o@uol.com.br",
    to: "akirlin1o@columbia.edu",
    body: "Suspendisse potenti. Nullam porttitor lacus at turpis.",
    date: "2020-02-20T19:56:40Z",
  },
  {
    id: 62,
    from: "jswett1p@ucoz.ru",
    to: "adomelow1p@mail.ru",
    body: "Morbi porttitor lorem id ligula.",
    date: "2020-02-09T18:40:33Z",
  },
  {
    id: 63,
    from: "colivas1q@geocities.com",
    to: "cwhiteland1q@thetimes.co.uk",
    body:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    date: "2019-10-15T12:04:46Z",
  },
  {
    id: 64,
    from: "jmerriman1r@engadget.com",
    to: "ocawthorne1r@umn.edu",
    body: "Nunc purus. Phasellus in felis.",
    date: "2019-12-05T11:42:39Z",
  },
  {
    id: 65,
    from: "fgeorgel1s@moonfruit.com",
    to: "rrobion1s@craigslist.org",
    body:
      "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    date: "2020-04-25T13:50:57Z",
  },
  {
    id: 66,
    from: "emurty1t@scientificamerican.com",
    to: "vcawcutt1t@shutterfly.com",
    body: "Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    date: "2020-02-15T11:41:41Z",
  },
  {
    id: 67,
    from: "gpowder1u@creativecommons.org",
    to: "rturneux1u@w3.org",
    body: "Quisque ut erat.",
    date: "2019-09-07T07:13:25Z",
  },
  {
    id: 68,
    from: "cstquentin1v@samsung.com",
    to: "jhandrahan1v@clickbank.net",
    body:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    date: "2019-06-22T05:51:41Z",
  },
  {
    id: 69,
    from: "rwoosnam1w@phpbb.com",
    to: "jcordova1w@miibeian.gov.cn",
    body:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    date: "2019-07-09T01:45:36Z",
  },
  {
    id: 70,
    from: "khuyge1x@naver.com",
    to: "grubes1x@opera.com",
    body:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
    date: "2019-10-20T18:27:50Z",
  },
  {
    id: 71,
    from: "wyouell1y@oakley.com",
    to: "bmoukes1y@google.ca",
    body:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.",
    date: "2019-06-16T12:15:24Z",
  },
  {
    id: 72,
    from: "mlandeaux1z@blinklist.com",
    to: "cpizzie1z@cbsnews.com",
    body: "In quis justo. Maecenas rhoncus aliquam lacus.",
    date: "2019-09-08T02:35:07Z",
  },
  {
    id: 73,
    from: "xwabersich20@redcross.org",
    to: "hlangwade20@vistaprint.com",
    body:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    date: "2019-09-09T11:01:39Z",
  },
  {
    id: 74,
    from: "swolters21@oracle.com",
    to: "tforri21@facebook.com",
    body: "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    date: "2019-05-05T12:09:19Z",
  },
  {
    id: 75,
    from: "straut22@irs.gov",
    to: "rtownby22@stanford.edu",
    body: "In hac habitasse platea dictumst.",
    date: "2020-01-21T06:31:40Z",
  },
  {
    id: 76,
    from: "lbagniuk23@edublogs.org",
    to: "fmarte23@mlb.com",
    body: "Integer a nibh. In quis justo.",
    date: "2020-02-27T13:07:29Z",
  },
  {
    id: 77,
    from: "jgatecliff24@paginegialle.it",
    to: "jgeroldo24@scribd.com",
    body:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    date: "2020-02-26T07:25:16Z",
  },
  {
    id: 78,
    from: "rgittose25@odnoklassniki.ru",
    to: "wpashba25@about.me",
    body: "In congue.",
    date: "2019-12-10T17:05:22Z",
  },
  {
    id: 79,
    from: "hpolino26@census.gov",
    to: "bsinclair26@1und1.de",
    body: "Sed vel enim sit amet nunc viverra dapibus.",
    date: "2019-10-11T04:56:32Z",
  },
  {
    id: 80,
    from: "ginger27@dropbox.com",
    to: "bohern27@e-recht24.de",
    body: "Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    date: "2019-09-03T08:33:36Z",
  },
  {
    id: 81,
    from: "pmongenot28@mtv.com",
    to: "mjedrzejewski28@hugedomains.com",
    body: "Quisque ut erat.",
    date: "2019-05-10T00:37:26Z",
  },
  {
    id: 82,
    from: "rfranchi29@zdnet.com",
    to: "lsimpkin29@reuters.com",
    body: "Integer ac leo. Pellentesque ultrices mattis odio.",
    date: "2019-07-21T03:10:34Z",
  },
  {
    id: 83,
    from: "joldfieldcherry2a@alibaba.com",
    to: "fmasic2a@a8.net",
    body: "Vivamus tortor. Duis mattis egestas metus.",
    date: "2020-01-04T03:02:15Z",
  },
  {
    id: 84,
    from: "gbrozsset2b@oakley.com",
    to: "thardypiggin2b@engadget.com",
    body: "Nulla nisl.",
    date: "2019-11-24T21:59:41Z",
  },
  {
    id: 85,
    from: "dlayne2c@sciencedirect.com",
    to: "mwitherop2c@shareasale.com",
    body: "Nullam varius. Nulla facilisi.",
    date: "2020-01-02T21:44:49Z",
  },
  {
    id: 86,
    from: "lwalters2d@prnewswire.com",
    to: "btarrant2d@earthlink.net",
    body: "In eleifend quam a odio.",
    date: "2019-12-08T06:15:52Z",
  },
  {
    id: 87,
    from: "efayerbrother2e@squarespace.com",
    to: "ngrabeham2e@smugmug.com",
    body: "Nulla mollis molestie lorem. Quisque ut erat.",
    date: "2019-08-05T08:12:55Z",
  },
  {
    id: 88,
    from: "jaarons2f@ibm.com",
    to: "mtemperley2f@flavors.me",
    body: "Duis mattis egestas metus. Aenean fermentum.",
    date: "2020-03-22T12:03:23Z",
  },
  {
    id: 89,
    from: "adunklee2g@dyndns.org",
    to: "atrengove2g@comcast.net",
    body: "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    date: "2019-07-16T06:18:54Z",
  },
  {
    id: 90,
    from: "hfincham2h@homestead.com",
    to: "khens2h@illinois.edu",
    body: "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    date: "2020-03-05T03:50:08Z",
  },
  {
    id: 91,
    from: "lharraway2i@squidoo.com",
    to: "twellard2i@privacy.gov.au",
    body:
      "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    date: "2019-10-10T11:20:14Z",
  },
  {
    id: 92,
    from: "oburder2j@ft.com",
    to: "bpetican2j@earthlink.net",
    body:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    date: "2019-10-20T17:48:58Z",
  },
  {
    id: 93,
    from: "apieroni2k@weather.com",
    to: "scarlozzi2k@businesswire.com",
    body: "Quisque porta volutpat erat.",
    date: "2020-04-18T11:53:32Z",
  },
  {
    id: 94,
    from: "lcapponer2l@who.int",
    to: "fnabbs2l@state.tx.us",
    body: "Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    date: "2019-06-01T06:57:57Z",
  },
  {
    id: 95,
    from: "tsattin2m@google.com.hk",
    to: "rtheriot2m@vinaora.com",
    body: "Morbi a ipsum. Integer a nibh.",
    date: "2019-06-12T09:39:21Z",
  },
  {
    id: 96,
    from: "acorney2n@jugem.jp",
    to: "ichaston2n@cbsnews.com",
    body: "Praesent blandit lacinia erat.",
    date: "2019-09-17T18:54:58Z",
  },
  {
    id: 97,
    from: "jpoge2o@wikimedia.org",
    to: "lahrend2o@digg.com",
    body: "Vivamus vestibulum sagittis sapien.",
    date: "2019-06-05T23:59:40Z",
  },
  {
    id: 98,
    from: "dhallet2p@msn.com",
    to: "fmuirden2p@shareasale.com",
    body: "Nulla justo.",
    date: "2019-11-20T01:14:25Z",
  },
  {
    id: 99,
    from: "esumption2q@bing.com",
    to: "ghayller2q@sohu.com",
    body: "Ut at dolor quis odio consequat varius.",
    date: "2019-11-08T21:27:28Z",
  },
  {
    id: 100,
    from: "cmcreath2r@forbes.com",
    to: "amcgettigan2r@mozilla.org",
    body: "Nulla tellus.",
    date: "2020-02-23T21:26:10Z",
  },
];
