export const mockdata = [
  {
    id: 1,
    from: "skenningham0@ezinearticles.com",
    to: "gfransson0@reference.com",
    body:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
    date: "2020-01-16 17:18:26",
  },
  {
    id: 2,
    from: "bcarrane1@liveinternet.ru",
    to: "esmithyman1@indiatimes.com",
    body: "Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    date: "2019-12-16 19:05:15",
  },
  {
    id: 3,
    from: "bangove2@arstechnica.com",
    to: "hsummerlee2@w3.org",
    body: "Integer ac leo.",
    date: "2020-03-19 23:15:27",
  },
  {
    id: 4,
    from: "nsircomb3@jimdo.com",
    to: "iorr3@wiley.com",
    body:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    date: "2019-12-28 14:04:57",
  },
  {
    id: 5,
    from: "aosband4@cocolog-nifty.com",
    to: "rbunstone4@ebay.com",
    body: "Morbi quis tortor id nulla ultrices aliquet.",
    date: "2020-01-02 00:16:39",
  },
  {
    id: 6,
    from: "ldacey5@drupal.org",
    to: "mtampion5@wix.com",
    body: "Aenean sit amet justo. Morbi ut odio.",
    date: "2020-03-26 14:16:21",
  },
  {
    id: 7,
    from: "bcronk6@google.fr",
    to: "faizik6@icq.com",
    body: "In sagittis dui vel nisl.",
    date: "2019-12-18 19:54:01",
  },
  {
    id: 8,
    from: "ctuddall7@ebay.com",
    to: "dtivolier7@census.gov",
    body: "Aenean lectus.",
    date: "2020-04-10 12:54:56",
  },
  {
    id: 9,
    from: "kswyne8@usda.gov",
    to: "cwarlton8@reuters.com",
    body: "Suspendisse potenti.",
    date: "2019-12-01 18:33:47",
  },
  {
    id: 10,
    from: "ncrumbie9@zimbio.com",
    to: "tpetters9@sakura.ne.jp",
    body: "In quis justo. Maecenas rhoncus aliquam lacus.",
    date: "2020-03-31 06:53:28",
  },
  {
    id: 11,
    from: "rcoveleya@phoca.cz",
    to: "dgodarda@sohu.com",
    body: "Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
    date: "2020-04-13 21:27:07",
  },
  {
    id: 12,
    from: "bgraylandb@mashable.com",
    to: "nferruzzib@ucsd.edu",
    body: "Aenean auctor gravida sem.",
    date: "2020-01-05 09:08:20",
  },
  {
    id: 13,
    from: "ycurlessc@answers.com",
    to: "bsherync@admin.ch",
    body: "Aenean lectus.",
    date: "2020-02-21 23:52:06",
  },
  {
    id: 14,
    from: "fburtenshawd@techcrunch.com",
    to: "cnusseyd@dagondesign.com",
    body: "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
    date: "2020-03-08 07:06:06",
  },
  {
    id: 15,
    from: "cpidducke@sciencedaily.com",
    to: "mchezellee@sakura.ne.jp",
    body: "Sed accumsan felis.",
    date: "2020-01-11 17:17:09",
  },
  {
    id: 16,
    from: "aworboyf@soundcloud.com",
    to: "cvanlintf@engadget.com",
    body: "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",
    date: "2020-04-20 02:49:26",
  },
  {
    id: 17,
    from: "dgladdisg@psu.edu",
    to: "cadamoug@samsung.com",
    body: "Praesent id massa id nisl venenatis lacinia.",
    date: "2020-03-14 00:43:35",
  },
  {
    id: 18,
    from: "cgydeh@merriam-webster.com",
    to: "zdelveh@china.com.cn",
    body: "Suspendisse potenti.",
    date: "2019-12-26 00:04:54",
  },
  {
    id: 19,
    from: "crisleyi@hostgator.com",
    to: "vmckeagi@rakuten.co.jp",
    body:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    date: "2020-03-04 12:52:58",
  },
  {
    id: 20,
    from: "cschuhj@nifty.com",
    to: "eegglesonj@imdb.com",
    body: "Nulla mollis molestie lorem.",
    date: "2020-02-25 07:44:08",
  },
  {
    id: 21,
    from: "kpetrukk@technorati.com",
    to: "ajellicok@istockphoto.com",
    body: "Mauris sit amet eros.",
    date: "2020-01-27 07:20:47",
  },
  {
    id: 22,
    from: "aohearnl@amazon.co.jp",
    to: "wobeel@europa.eu",
    body: "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    date: "2019-12-11 06:32:54",
  },
  {
    id: 23,
    from: "okilleleym@chicagotribune.com",
    to: "sfarresm@eepurl.com",
    body: "Nunc purus. Phasellus in felis.",
    date: "2020-04-26 20:03:51",
  },
  {
    id: 24,
    from: "rhorseyn@live.com",
    to: "mdelosn@hostgator.com",
    body: "Praesent blandit. Nam nulla.",
    date: "2020-02-14 02:57:42",
  },
  {
    id: 25,
    from: "ibodimeadeo@ycombinator.com",
    to: "bniezeno@sogou.com",
    body: "Duis consequat dui nec nisi volutpat eleifend.",
    date: "2020-01-28 11:30:02",
  },
  {
    id: 26,
    from: "lhackettp@smh.com.au",
    to: "tdenfordp@ftc.gov",
    body: "In hac habitasse platea dictumst.",
    date: "2020-04-27 15:37:28",
  },
  {
    id: 27,
    from: "skennicottq@loc.gov",
    to: "dvickarq@blogspot.com",
    body:
      "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    date: "2020-02-06 01:38:00",
  },
  {
    id: 28,
    from: "cbrigger@twitter.com",
    to: "hcurgenvenr@stanford.edu",
    body: "Proin at turpis a pede posuere nonummy.",
    date: "2019-12-24 06:12:35",
  },
  {
    id: 29,
    from: "tcaffreys@squidoo.com",
    to: "mwyleys@ebay.co.uk",
    body:
      "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    date: "2020-02-17 13:20:23",
  },
  {
    id: 30,
    from: "mwalshet@theglobeandmail.com",
    to: "ccollert@ovh.net",
    body: "Aliquam erat volutpat. In congue.",
    date: "2020-03-01 23:07:48",
  },
  {
    id: 31,
    from: "mbarthelmesu@arizona.edu",
    to: "sbremeyeru@shutterfly.com",
    body: "Vivamus tortor.",
    date: "2020-04-13 15:43:43",
  },
  {
    id: 32,
    from: "gmenghiv@wix.com",
    to: "vewbanckv@prnewswire.com",
    body: "Phasellus sit amet erat.",
    date: "2020-02-05 18:07:08",
  },
  {
    id: 33,
    from: "grostronw@netlog.com",
    to: "grisebarerw@github.io",
    body: "Aenean lectus. Pellentesque eget nunc.",
    date: "2019-12-20 23:10:51",
  },
  {
    id: 34,
    from: "ewadlowx@buzzfeed.com",
    to: "dworsfieldx@salon.com",
    body: "Morbi a ipsum.",
    date: "2020-04-21 16:52:07",
  },
  {
    id: 35,
    from: "yoroany@craigslist.org",
    to: "ebickery@independent.co.uk",
    body: "Morbi non lectus.",
    date: "2020-01-09 08:35:49",
  },
  {
    id: 36,
    from: "chighmanz@opensource.org",
    to: "dhorwellz@51.la",
    body: "Duis mattis egestas metus. Aenean fermentum.",
    date: "2020-02-20 20:19:22",
  },
  {
    id: 37,
    from: "jbaggs10@imgur.com",
    to: "cmeineking10@bloomberg.com",
    body: "Praesent blandit.",
    date: "2020-01-12 16:27:42",
  },
  {
    id: 38,
    from: "zstothart11@whitehouse.gov",
    to: "mreinmar11@wunderground.com",
    body: "Vestibulum sed magna at nunc commodo placerat.",
    date: "2020-01-20 09:41:19",
  },
  {
    id: 39,
    from: "lbrisland12@constantcontact.com",
    to: "sholdren12@cmu.edu",
    body: "Cras in purus eu magna vulputate luctus.",
    date: "2020-04-02 03:25:30",
  },
  {
    id: 40,
    from: "kcarne13@github.io",
    to: "tfeckey13@deviantart.com",
    body: "Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    date: "2020-01-15 00:48:38",
  },
  {
    id: 41,
    from: "jdunnan14@senate.gov",
    to: "ewolfit14@wsj.com",
    body: "Suspendisse accumsan tortor quis turpis. Sed ante.",
    date: "2019-12-11 16:53:04",
  },
  {
    id: 42,
    from: "hblaxley15@cornell.edu",
    to: "lsully15@house.gov",
    body:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    date: "2020-02-26 03:31:08",
  },
  {
    id: 43,
    from: "bwickman16@japanpost.jp",
    to: "wchampneys16@slate.com",
    body:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    date: "2020-04-17 16:21:59",
  },
  {
    id: 44,
    from: "ktowndrow17@unesco.org",
    to: "bdeaves17@youku.com",
    body: "Aliquam erat volutpat. In congue.",
    date: "2019-12-26 03:01:18",
  },
  {
    id: 45,
    from: "ewallbank18@godaddy.com",
    to: "jgeorgeau18@hc360.com",
    body:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    date: "2020-03-11 07:38:12",
  },
  {
    id: 46,
    from: "rgrouse19@eepurl.com",
    to: "fdabell19@stumbleupon.com",
    body: "Nunc purus.",
    date: "2019-12-17 20:02:24",
  },
  {
    id: 47,
    from: "bfeechan1a@sakura.ne.jp",
    to: "ljoye1a@dailymail.co.uk",
    body: "Nam nulla.",
    date: "2019-12-28 01:09:27",
  },
  {
    id: 48,
    from: "gradnedge1b@mozilla.org",
    to: "smccurdy1b@youtube.com",
    body: "Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
    date: "2020-03-26 21:39:35",
  },
  {
    id: 49,
    from: "ooxtaby1c@liveinternet.ru",
    to: "vbollom1c@scribd.com",
    body:
      "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    date: "2020-04-09 17:09:26",
  },
  {
    id: 50,
    from: "thazael1d@wisc.edu",
    to: "uelford1d@amazon.co.jp",
    body: "Nulla ac enim.",
    date: "2020-04-27 21:45:19",
  },
  {
    id: 51,
    from: "meliot1e@topsy.com",
    to: "djako1e@blogspot.com",
    body:
      "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    date: "2020-04-23 04:40:01",
  },
  {
    id: 52,
    from: "askeete1f@princeton.edu",
    to: "hkinkead1f@ftc.gov",
    body:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    date: "2020-04-01 13:08:57",
  },
  {
    id: 53,
    from: "vwenderott1g@pagesperso-orange.fr",
    to: "momara1g@wsj.com",
    body: "Praesent blandit. Nam nulla.",
    date: "2020-01-03 00:03:51",
  },
  {
    id: 54,
    from: "jcossell1h@tinypic.com",
    to: "hsearight1h@shop-pro.jp",
    body:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    date: "2019-12-21 01:12:24",
  },
  {
    id: 55,
    from: "rmabey1i@github.com",
    to: "lubanks1i@cam.ac.uk",
    body: "Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    date: "2020-01-14 22:06:18",
  },
  {
    id: 56,
    from: "lmonan1j@1und1.de",
    to: "jpaulus1j@phpbb.com",
    body:
      "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    date: "2020-03-24 13:14:39",
  },
  {
    id: 57,
    from: "dmcgavin1k@princeton.edu",
    to: "nhysom1k@kickstarter.com",
    body: "In hac habitasse platea dictumst.",
    date: "2020-04-25 06:39:09",
  },
  {
    id: 58,
    from: "jplain1l@google.pl",
    to: "mabrahams1l@dyndns.org",
    body: "Suspendisse potenti. Nullam porttitor lacus at turpis.",
    date: "2020-02-01 13:46:55",
  },
  {
    id: 59,
    from: "cheady1m@4shared.com",
    to: "bspowart1m@accuweather.com",
    body:
      "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    date: "2020-04-04 00:48:42",
  },
  {
    id: 60,
    from: "lgarretts1n@elpais.com",
    to: "dratchford1n@google.com.hk",
    body:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    date: "2020-03-12 04:11:27",
  },
  {
    id: 61,
    from: "vridde1o@dot.gov",
    to: "hhannaway1o@ca.gov",
    body: "Donec semper sapien a libero.",
    date: "2020-01-27 22:40:51",
  },
  {
    id: 62,
    from: "vdaunay1p@google.fr",
    to: "dscotsbrook1p@facebook.com",
    body:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.",
    date: "2020-04-12 04:46:42",
  },
  {
    id: 63,
    from: "aserginson1q@jimdo.com",
    to: "mcaherny1q@free.fr",
    body:
      "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    date: "2020-01-02 11:28:24",
  },
  {
    id: 64,
    from: "adavidson1r@tuttocitta.it",
    to: "oambridge1r@kickstarter.com",
    body: "Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    date: "2019-12-11 03:27:18",
  },
  {
    id: 65,
    from: "ehay1s@tuttocitta.it",
    to: "rgardener1s@cafepress.com",
    body: "Curabitur convallis.",
    date: "2019-12-18 18:52:11",
  },
  {
    id: 66,
    from: "atesimon1t@goo.gl",
    to: "agerb1t@thetimes.co.uk",
    body:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    date: "2019-12-22 17:12:46",
  },
  {
    id: 67,
    from: "caitcheson1u@vkontakte.ru",
    to: "tdempster1u@cdc.gov",
    body: "Vivamus vestibulum sagittis sapien.",
    date: "2019-12-02 16:37:18",
  },
  {
    id: 68,
    from: "aoldroyde1v@oracle.com",
    to: "acastanho1v@shop-pro.jp",
    body:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    date: "2020-01-21 11:13:42",
  },
  {
    id: 69,
    from: "iiglesia1w@ucoz.ru",
    to: "jfasson1w@china.com.cn",
    body:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    date: "2020-04-15 08:25:20",
  },
  {
    id: 70,
    from: "cfuchs1x@google.es",
    to: "nmayow1x@domainmarket.com",
    body:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    date: "2020-01-24 14:27:30",
  },
  {
    id: 71,
    from: "ddrakes1y@simplemachines.org",
    to: "rcheavin1y@europa.eu",
    body: "Integer ac leo.",
    date: "2019-12-01 21:22:13",
  },
  {
    id: 72,
    from: "cmenicomb1z@cloudflare.com",
    to: "tcaret1z@joomla.org",
    body: "Aenean lectus.",
    date: "2019-12-14 09:12:43",
  },
  {
    id: 73,
    from: "lneiland20@elegantthemes.com",
    to: "lwinslett20@imdb.com",
    body: "Aenean lectus. Pellentesque eget nunc.",
    date: "2020-04-20 11:56:01",
  },
  {
    id: 74,
    from: "fcamelia21@com.com",
    to: "nscanlon21@privacy.gov.au",
    body: "Nulla facilisi.",
    date: "2020-01-05 20:43:21",
  },
  {
    id: 75,
    from: "cloughead22@alibaba.com",
    to: "veede22@ehow.com",
    body:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    date: "2019-12-04 11:53:07",
  },
  {
    id: 76,
    from: "mhixson23@ucla.edu",
    to: "cshew23@dell.com",
    body:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    date: "2019-12-20 18:08:31",
  },
  {
    id: 77,
    from: "dcorrington24@sakura.ne.jp",
    to: "cwarne24@bigcartel.com",
    body: "Duis mattis egestas metus. Aenean fermentum.",
    date: "2020-03-24 19:09:09",
  },
  {
    id: 78,
    from: "astayt25@topsy.com",
    to: "mtooker25@nifty.com",
    body: "Vivamus tortor. Duis mattis egestas metus.",
    date: "2020-04-03 05:43:15",
  },
  {
    id: 79,
    from: "smetcalfe26@barnesandnoble.com",
    to: "hpaolucci26@xrea.com",
    body: "Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    date: "2020-02-11 00:01:55",
  },
  {
    id: 80,
    from: "glast27@prlog.org",
    to: "sclaussen27@aboutads.info",
    body: "Quisque id justo sit amet sapien dignissim vestibulum.",
    date: "2020-04-05 19:36:42",
  },
  {
    id: 81,
    from: "rnasey28@cnbc.com",
    to: "syosselevitch28@barnesandnoble.com",
    body: "Aliquam erat volutpat. In congue.",
    date: "2020-01-17 17:40:29",
  },
  {
    id: 82,
    from: "vdeevey29@sbwire.com",
    to: "adayley29@accuweather.com",
    body:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    date: "2019-12-21 20:37:26",
  },
  {
    id: 83,
    from: "hhaydock2a@scientificamerican.com",
    to: "rbigrigg2a@telegraph.co.uk",
    body:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    date: "2020-03-05 02:18:00",
  },
  {
    id: 84,
    from: "nfilinkov2b@gnu.org",
    to: "cdemcak2b@aboutads.info",
    body: "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.",
    date: "2020-01-20 01:55:20",
  },
  {
    id: 85,
    from: "jway2c@domainmarket.com",
    to: "hbengough2c@canalblog.com",
    body:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    date: "2019-12-31 20:07:57",
  },
  {
    id: 86,
    from: "lcrafter2d@salon.com",
    to: "abordone2d@topsy.com",
    body: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    date: "2020-02-07 22:10:31",
  },
  {
    id: 87,
    from: "gboyet2e@fastcompany.com",
    to: "wbabst2e@mit.edu",
    body:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    date: "2020-03-13 10:32:48",
  },
  {
    id: 88,
    from: "edows2f@wisc.edu",
    to: "aoloughane2f@answers.com",
    body:
      "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    date: "2020-02-15 21:48:21",
  },
  {
    id: 89,
    from: "fwardell2g@pcworld.com",
    to: "gthorwarth2g@blogtalkradio.com",
    body: "Maecenas tincidunt lacus at velit.",
    date: "2020-01-14 14:47:20",
  },
  {
    id: 90,
    from: "gjuett2h@admin.ch",
    to: "nvigar2h@soup.io",
    body: "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    date: "2020-02-07 18:36:07",
  },
  {
    id: 91,
    from: "fharkins2i@themeforest.net",
    to: "grotter2i@moonfruit.com",
    body:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    date: "2019-12-05 14:03:58",
  },
  {
    id: 92,
    from: "jcarwithim2j@washingtonpost.com",
    to: "pbritee2j@vkontakte.ru",
    body: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    date: "2020-03-11 08:47:10",
  },
  {
    id: 93,
    from: "lskoggins2k@dropbox.com",
    to: "hbutlin2k@amazon.co.uk",
    body: "Aliquam non mauris.",
    date: "2020-02-08 13:35:42",
  },
  {
    id: 94,
    from: "cbarnby2l@bloglovin.com",
    to: "wcaghy2l@comcast.net",
    body:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    date: "2020-02-08 04:43:19",
  },
  {
    id: 95,
    from: "mgoldster2m@miibeian.gov.cn",
    to: "mloding2m@acquirethisname.com",
    body: "Integer ac leo.",
    date: "2020-01-26 11:37:36",
  },
  {
    id: 96,
    from: "acaswall2n@cisco.com",
    to: "cenrico2n@stanford.edu",
    body: "Aenean sit amet justo. Morbi ut odio.",
    date: "2020-04-14 12:30:29",
  },
  {
    id: 97,
    from: "hpilipyak2o@etsy.com",
    to: "ghansley2o@shutterfly.com",
    body:
      "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    date: "2019-12-10 17:20:33",
  },
  {
    id: 98,
    from: "gcastleton2p@cam.ac.uk",
    to: "mhulles2p@tripod.com",
    body: "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    date: "2020-02-25 07:36:57",
  },
  {
    id: 99,
    from: "ctreadger2q@facebook.com",
    to: "oyushkov2q@cisco.com",
    body: "Donec ut dolor.",
    date: "2020-04-29 10:50:10",
  },
  {
    id: 100,
    from: "afrancioli2r@reference.com",
    to: "hwhiteside2r@arizona.edu",
    body:
      "Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    date: "2020-04-29 01:54:40",
  },
];
